"""create sales table

Revision ID: 23cf83d5a804
Revises: dc925ce1ecd0
Create Date: 2025-09-25 19:52:31.245690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cf83d5a804'
down_revision = 'dc925ce1ecd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_sales_inventory_id', 'inventory', ['inventory_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint('fk_sales_inventory_id', type_='foreignkey')
        batch_op.drop_column('inventory_id')

    # ### end Alembic commands ###
