"""Add avatar_url and gender to User

Revision ID: 450237f538ae
Revises: dd7aea744228
Create Date: 2025-09-20 19:45:13.441090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450237f538ae'
down_revision = 'dd7aea744228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
