"""Add avatar_url and gender to User

Revision ID: a5484ea7eace
Revises: 450237f538ae
Create Date: 2025-09-20 19:46:23.062317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5484ea7eace'
down_revision = '450237f538ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
