"""Add Sale table

Revision ID: ae9eb5389465
Revises: 23cf83d5a804
Create Date: 2025-09-25 23:24:30.398640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9eb5389465'
down_revision = '23cf83d5a804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_sales_employee_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_inventory_id'), type_='foreignkey')
        batch_op.drop_column('price')
        batch_op.drop_column('date')
        batch_op.drop_column('inventory_id')
        batch_op.drop_column('commission')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('quantity')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('commission', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('inventory_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_sales_inventory_id'), 'inventory', ['inventory_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_employee_id'), 'employees', ['employee_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('total')

    op.drop_table('sale_items')
    # ### end Alembic commands ###
