"""Add role column to users

Revision ID: cb7e8c5a0cb2
Revises: ccd798b006c5
Create Date: 2025-09-18 22:38:18.733565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7e8c5a0cb2'
down_revision = 'ccd798b006c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_verification_token'))
        batch_op.drop_column('is_verified')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_verification_token'), ['verification_token'], unique=False)
        batch_op.drop_column('role')

    # ### end Alembic commands ###
