"""Add Sale model with named FK

Revision ID: db80fe70a385
Revises: 5c9d92434c49
Create Date: 2025-09-25 13:19:00.992864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db80fe70a385'
down_revision = '5c9d92434c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_foreign_key('fk_sales_employee_id', 'employees', ['employee_id'], ['id'])
        batch_op.drop_column('amount')
        batch_op.drop_column('item_name')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint('fk_sales_employee_id', type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('date')
        batch_op.drop_column('commission')
        batch_op.drop_column('discount')
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
